### ISSUE TITLE
请问，图片和视频拼接是如何实现的呀？

### ISSUE THREAD

**Issue by 008v** [LanSoSdk/video-edit-sdk-ios#1]
AVComposition并不支持图片，是自定义Instruction后，把图片保存到Instruction里的吗？

**Comment by LanSoSdk** [comment]
我们做的是商用SDK, 是付费的. 

我们做了一个容器, 可以让你把图片和视频拼接增加进去, 然后导出即可.

**Comment by 008v** [comment]
> 我们做的是商用SDK, 是付费的.
> 
> 我们做了一个容器, 可以让你把图片和视频拼接增加进去, 然后导出即可.

好吧。看起来并没从技术角度回答。
我自己研究研究吧。
